apiVersion: v1
kind: List
items:

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: adop-nginx
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: adop-nginx
      spec:
        containers:
        - name: adop-nginx
          image: lumaks/adop-nginx
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          env:
          - name: LDAP_PROTOCOL
            value: ldaps
          - name: LDAP_SERVER
            value: sr1puimnl10
          - name: LDAP_USER_BASE_DN
            value: OU=people,DC=ipc,DC=biz
          - name: LDAP_USER_ID_ATTRIBUTE
            value: uid
          - name: LDAP_USER_OBJECT_CLASS
            value: '*'
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo '172.16.85.45 sr1puimnl10'>> /etc/hosts"]

- apiVersion: v1
  kind: Service
  metadata:
    name: adop-nginx
  spec:
    selector:
      app: adop-nginx
    ports:
    - name: secure
      port: 443
      protocol: TCP
      targetPort: 443
    - name: insecure
      port: 80
      protocol: TCP
      targetPort: 80
    type: NodePort
